print("Welcome to the Band Name Generator")
city = input("Enter the name of the city you grew up in: ")
print(city)
pet = input("Enter the name of a pet: ")
print(pet)
print("Your band name could be " + city + " " + pet)
